// packages/vue/src/Heelslide.vue
<script setup lang="ts">
import { ref, computed, onUnmounted, useId } from 'vue';
import { KEY_SHORTCUTS, getStepDirection, resolveKeyAction, type Point2D } from '@heelslide/core';
import type { HeelslideProps, HeelslideEmits } from './types.js';
import { useHeelslide } from './useHeelslide.js';
import './style.css';

const props = withDefaults(defineProps<HeelslideProps>(), {
  heels: 2,
  tolerance: 24,
  bounds: () => ({ width: 300, height: 150 }),
  gridStep: 24,
  margin: 16,
  disabled: false,
  numberedHeels: false,
  segmented: false,
  checkpointTimeoutMs: 0,
  ariaLabel: 'Slide to unlock'
});

const emit = defineEmits<HeelslideEmits>();

const stepped = computed(() => (props.accessibleFallback ?? 'stepped') === 'stepped');
const descriptionId = `heelslide-desc-${useId()}`;

const containerRef = ref<HTMLElement | null>(null);
const handleRef = ref<SVGGElement | null>(null);
const capturedPointerId = ref<number | null>(null);

const {
  state,
  progress,
  track,
  currentSegmentIndex,
  handlePosition,
  isDragging,
  startGesture,
  updateGesture,
  endGesture,
  cancelGesture,
  reset,
  regeneratePath,
  stepForward,
  stepBackward,
  description,
  announcement
} = useHeelslide({
  track: props.track,
  tolerance: props.tolerance,
  initialState: props.initialState,
  initialProgress: props.initialProgress,
  segmented: props.segmented,
  checkpointTimeoutMs: props.checkpointTimeoutMs,
  generator: {
    bounds: props.bounds,
    gridStep: props.gridStep,
    margin: props.margin,
    heels: props.heels,
    seed: props.seed
  },
  haptics: props.haptics,
  sound: props.sound,
  containerRef,
  onTurn: (heelIndex) => {
    emit('turn', heelIndex);
    props.onTurn?.(heelIndex);
  },
  onCheckpoint: (heelIndex, p) => {
    emit('checkpoint', { heelIndex, progress: p });
    props.onCheckpoint?.(heelIndex, p);
  },
  onUnlock: () => {
    emit('unlock');
  },
  onReset: () => {
    emit('reset');
  },
  onProgress: (p) => {
    emit('progress', p);
  },
  onStateChange: (s) => {
    emit('stateChange', s);
  },
  onAnnouncement: (a) => {
    emit('announcement', a);
  }
});

const activeSegment = computed(() => track.value.segments[currentSegmentIndex.value]);

const valueText = computed(() => {
  const percent = Math.round(progress.value * 100);
  const segment = activeSegment.value;
  if (!segment) return `${percent}% complete.`;
  const direction = getStepDirection(segment.start, segment.end, segment.direction);
  return `${percent}% complete. Move ${direction} to continue.`;
});

function handleKeyDown(event: KeyboardEvent): void {
  if (props.disabled || !stepped.value) return;

  const action = resolveKeyAction(event.key);
  if (!action) return;

  // Only claim keys we handle, so page scrolling and shortcuts survive elsewhere.
  event.preventDefault();

  switch (action) {
    case 'forward':
      stepForward();
      break;
    case 'backward':
      stepBackward();
      break;
    case 'reset':
    case 'cancel':
      reset();
      break;
    case 'confirm':
      endGesture();
      break;
  }
}

function pointsToSvgPath(points: readonly Point2D[]): string {
  if (points.length === 0) return '';
  const [first, ...rest] = points;
  return `M ${first!.x} ${first!.y} ${rest.map((p) => `L ${p.x} ${p.y}`).join(' ')}`.trim();
}

const bgPathD = computed(() => pointsToSvgPath(track.value.points));

const progressPathD = computed(() => {
  if (progress.value <= 0) {
    const startPt = track.value.points[0]!;
    return `M ${startPt.x} ${startPt.y} L ${startPt.x} ${startPt.y}`;
  }

  const traversedPoints = track.value.points.slice(0, currentSegmentIndex.value + 1);
  const pathPoints = [...traversedPoints, handlePosition.value];
  return pointsToSvgPath(pathPoints);
});

const heelMarkers = computed(() => {
  if (track.value.points.length <= 2) return [];
  return track.value.points.slice(1, -1);
});

const destinationPoint = computed(() => {
  return track.value.points[track.value.points.length - 1]!;
});

const isGoalTarget = computed(() => {
  return track.value.points.length > 0 && currentSegmentIndex.value >= track.value.points.length - 2;
});

const viewBox = computed(() => {
  return `0 0 ${props.bounds.width} ${props.bounds.height}`;
});

function handlePointerDown(event: PointerEvent): void {
  if (props.disabled) return;

  const target = event.currentTarget as Element | null;
  if (target && typeof target.setPointerCapture === 'function') {
    try {
      target.setPointerCapture(event.pointerId);
      capturedPointerId.value = event.pointerId;
    } catch {
      // Ignore pointer capture error in test environments
    }
  }

  startGesture(event);
}

function handlePointerMove(event: PointerEvent): void {
  if (props.disabled || !isDragging.value) return;
  updateGesture(event);
}

function handlePointerUp(event: PointerEvent): void {
  if (props.disabled) return;

  const target = event.currentTarget as Element | null;
  if (target && capturedPointerId.value !== null && typeof target.releasePointerCapture === 'function') {
    try {
      target.releasePointerCapture(capturedPointerId.value);
    } catch {
      // Ignore pointer release error
    }
    capturedPointerId.value = null;
  }

  if (isDragging.value) {
    endGesture();
  }
}

function handlePointerCancel(event: PointerEvent): void {
  if (props.disabled) return;

  const target = event.currentTarget as Element | null;
  if (target && capturedPointerId.value !== null && typeof target.releasePointerCapture === 'function') {
    try {
      target.releasePointerCapture(capturedPointerId.value);
    } catch {
      // Ignore pointer release error
    }
    capturedPointerId.value = null;
  }

  if (isDragging.value) {
    cancelGesture();
  }
}

onUnmounted(() => {
  if (isDragging.value) {
    cancelGesture();
  }
  capturedPointerId.value = null;
});

defineExpose({
  state,
  progress,
  track,
  currentSegmentIndex,
  handlePosition,
  reset,
  regeneratePath
});
</script>

<template>
  <div
    ref="containerRef"
    class="heelslide-container"
    :class="{
      'heelslide-disabled': disabled,
      'heelslide-active': isDragging,
      'heelslide-checkpoint': state === 'checkpoint',
      'heelslide-unlocked': state === 'unlocked'
    }"
    role="slider"
    :aria-label="ariaLabel"
    :aria-valuemin="0"
    :aria-valuemax="100"
    :aria-valuenow="Math.round(progress * 100)"
    :aria-valuetext="valueText"
    :aria-orientation="activeSegment?.direction ?? 'horizontal'"
    :aria-disabled="disabled"
    :aria-describedby="descriptionId"
    :aria-keyshortcuts="stepped ? KEY_SHORTCUTS : undefined"
    :tabindex="disabled ? -1 : 0"
    :data-disabled="disabled"
    :data-state="state"
    data-heelslide-container
    @keydown="handleKeyDown"
    :style="{
      '--heelslide-width': `${bounds.width}px`,
      '--heelslide-height': `${bounds.height}px`
    }"
  >
    <svg
      class="heelslide-svg"
      :viewBox="viewBox"
      xmlns="http://www.w3.org/2000/svg"
    >
      <!-- Background track -->
      <path
        class="heelslide-track-bg"
        :d="bgPathD"
      />

      <!-- Progress path overlay -->
      <path
        class="heelslide-track-progress"
        :d="progressPathD"
      />

      <!-- Heel turn markers -->
      <g
        v-for="(marker, index) in heelMarkers"
        :key="`heel-${index}`"
        class="heelslide-heel-group"
        :class="{
          'heelslide-target': currentSegmentIndex === index,
          'heelslide-cleared': currentSegmentIndex > index
        }"
        :data-heelslide-heel="index + 1"
        :data-target="currentSegmentIndex === index ? 'true' : 'false'"
      >
        <!-- Clearance buffer ring -->
        <circle
          class="heelslide-heel-buffer"
          :cx="marker.x"
          :cy="marker.y"
        />
        <!-- Heel marker circle -->
        <circle
          class="heelslide-heel-marker"
          :cx="marker.x"
          :cy="marker.y"
        />
        <!-- Numbered heel text label -->
        <text
          v-if="numberedHeels"
          class="heelslide-heel-text"
          :x="marker.x"
          :y="marker.y"
          text-anchor="middle"
          dominant-baseline="central"
        >
          {{ index + 1 }}
        </text>
      </g>

      <!-- Destination end marker -->
      <g
        class="heelslide-goal-group"
        :class="{ 'heelslide-target': isGoalTarget }"
        :data-target="isGoalTarget ? 'true' : 'false'"
      >
        <circle
          class="heelslide-end-marker"
          :cx="destinationPoint.x"
          :cy="destinationPoint.y"
        />
      </g>

      <!-- Draggable Handle -->
      <g
        ref="handleRef"
        class="heelslide-handle"
        @pointerdown="handlePointerDown"
        @pointermove="handlePointerMove"
        @pointerup="handlePointerUp"
        @pointercancel="handlePointerCancel"
      >
        <circle
          class="heelslide-handle-circle"
          :cx="handlePosition.x"
          :cy="handlePosition.y"
        />
        <slot
          name="handle"
          :position="handlePosition"
          :progress="progress"
          :state="state"
        />
      </g>
    </svg>

    <span :id="descriptionId" class="heelslide-visually-hidden">{{ description }}</span>

    <span
      v-if="stepped"
      data-heelslide-live-region
      role="status"
      aria-live="polite"
      aria-atomic="true"
      class="heelslide-visually-hidden"
    >
      <slot name="announcer" :announcement="announcement">{{ announcement?.message ?? '' }}</slot>
    </span>
  </div>
</template>

// packages/react/src/Heelslide.tsx
import { forwardRef, useCallback, useId, useMemo } from 'react';
import { KEY_SHORTCUTS, getStepDirection, resolveKeyAction } from '@heelslide/core';
import type { HeelslideProps } from './types';
import { useHeelslide } from './useHeelslide';

/**
 * Removes content from view while leaving it in the accessibility tree. `display: none` and
 * `visibility: hidden` would take it out of both.
 */
const visuallyHidden: React.CSSProperties = {
  position: 'absolute',
  width: 1,
  height: 1,
  padding: 0,
  margin: -1,
  overflow: 'hidden',
  clip: 'rect(0, 0, 0, 0)',
  whiteSpace: 'nowrap',
  border: 0
};

export const Heelslide = forwardRef<HTMLDivElement, HeelslideProps>(function Heelslide(
  props,
  ref
) {
  const {
    heels = 2,
    tolerance = 24,
    disabled = false,
    initialState,
    initialProgress,
    haptics,
    sound,
    segmented,
    checkpointTimeoutMs,
    onTurn,
    onCheckpoint,
    onUnlock,
    onReset,
    onProgress,
    onStateChange,
    numberedHeels = false,
    className,
    style,
    bounds,
    width,
    height,
    track: trackProp,
    gridStep = 24,
    margin = 16,
    seed,
    ariaLabel = 'Intentional gesture security gate',
    accessibleFallback = 'stepped',
    onAnnouncement,
    children
  } = props;

  // `bounds` is the cross-adapter prop; `width`/`height` remain as deprecated aliases.
  const resolvedWidth = bounds?.width ?? width ?? 300;
  const resolvedHeight = bounds?.height ?? height ?? 150;

  const generatorOptions = useMemo(
    () => ({
      bounds: { width: resolvedWidth, height: resolvedHeight },
      gridStep,
      margin,
      heels,
      seed
    }),
    [resolvedWidth, resolvedHeight, gridStep, margin, heels, seed]
  );

  const {
    state,
    progress,
    track,
    currentSegmentIndex,
    isDragging,
    getContainerProps,
    getHandleProps,
    stepForward,
    stepBackward,
    confirm,
    reset,
    description,
    announcement
  } = useHeelslide({
    tolerance,
    disabled,
    initialState,
    initialProgress,
    haptics,
    sound,
    segmented,
    checkpointTimeoutMs,
    generator: generatorOptions,
    track: trackProp,
    onTurn,
    onCheckpoint,
    onUnlock,
    onReset,
    onProgress,
    onStateChange,
    onAnnouncement
  });

  const containerProps = getContainerProps();
  const handleProps = getHandleProps();

  const stepped = accessibleFallback === 'stepped';

  // Stable per instance, so `aria-describedby` and the description node agree without a render
  // cycle in between.
  const descriptionId = useId();

  const handleKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      if (disabled || !stepped) return;

      const action = resolveKeyAction(event.key);
      if (!action) return;

      // Only claim keys we actually handle, so page scrolling and shortcuts survive elsewhere.
      event.preventDefault();

      switch (action) {
        case 'forward':
          stepForward();
          break;
        case 'backward':
          stepBackward();
          break;
        case 'reset':
        case 'cancel':
          reset();
          break;
        case 'confirm':
          confirm();
          break;
      }
    },
    [disabled, stepped, stepForward, stepBackward, reset, confirm]
  );

  const activeSegment = track.segments[currentSegmentIndex];
  const percent = Math.round(progress * 100);
  const valueText = activeSegment
    ? `${percent}% complete. Move ${getStepDirection(
        activeSegment.start,
        activeSegment.end,
        activeSegment.direction
      )} to continue.`
    : `${percent}% complete.`;

  const pathData = useMemo(() => {
    if (!track.points || track.points.length === 0) return '';
    return track.points
      .map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`)
      .join(' ');
  }, [track.points]);

  /**
   * Overlay describing exactly the traversed length, walking whole segments until the remaining
   * distance falls inside one and then interpolating along it.
   */
  const progressPathData = useMemo(() => {
    if (!track.points || track.points.length === 0 || track.totalLength <= 0) return '';

    const travelled = Math.min(1, Math.max(0, progress)) * track.totalLength;
    if (travelled <= 0) return '';

    const first = track.points[0]!;
    const commands = [`M ${first.x} ${first.y}`];
    let remaining = travelled;

    for (const segment of track.segments) {
      if (remaining >= segment.length) {
        commands.push(`L ${segment.end.x} ${segment.end.y}`);
        remaining -= segment.length;
        continue;
      }

      const t = segment.length > 0 ? remaining / segment.length : 0;
      const x = segment.start.x + t * (segment.end.x - segment.start.x);
      const y = segment.start.y + t * (segment.end.y - segment.start.y);
      commands.push(`L ${x} ${y}`);
      remaining = 0;
      break;
    }

    return commands.length > 1 ? commands.join(' ') : '';
  }, [track, progress]);

  const heelVertices = useMemo(() => {
    if (!track.points || track.points.length <= 2) return [];
    return track.points.slice(1, -1);
  }, [track.points]);

  const startPoint = track.points[0];
  const endPoint = track.points[track.points.length - 1];
  const isGoalTarget = track.points.length > 0 && currentSegmentIndex >= track.points.length - 2;

  return (
    <div
      ref={ref}
      role="slider"
      aria-label={ariaLabel}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-valuenow={percent}
      aria-valuetext={valueText}
      aria-orientation={activeSegment?.direction ?? 'horizontal'}
      aria-disabled={disabled}
      aria-describedby={descriptionId}
      {...(stepped ? { 'aria-keyshortcuts': KEY_SHORTCUTS } : {})}
      tabIndex={disabled ? -1 : 0}
      onKeyDown={handleKeyDown}
      data-disabled={disabled}
      data-state={state}
      data-heelslide-container
      className={className}
      style={{
        position: 'relative',
        width: `${resolvedWidth}px`,
        height: `${resolvedHeight}px`,
        counterReset: 'heelslide-heel',
        backgroundColor: 'var(--heelslide-bg, transparent)',
        borderRadius: 'var(--heelslide-border-radius, 12px)',
        userSelect: 'none',
        touchAction: 'none',
        overflow: 'hidden',
        boxSizing: 'border-box',
        ...style
      }}
      {...containerProps}
    >
      <svg
        viewBox={`0 0 ${resolvedWidth} ${resolvedHeight}`}
        width="100%"
        height="100%"
        style={{
          display: 'block',
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          pointerEvents: 'none'
        }}
      >
        {/* Background track path */}
        {pathData && (
          <path
            data-heelslide-track="background"
            d={pathData}
            stroke="var(--heelslide-track-bg, #e2e8f0)"
            strokeWidth="var(--heelslide-track-width, 12px)"
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
        )}

        {/* Traversed progress overlay */}
        <path
          data-heelslide-track="progress"
          className="heelslide-track-progress"
          d={progressPathData}
          stroke="var(--heelslide-track-progress, var(--heelslide-track-active, #3b82f6))"
          strokeWidth="var(--heelslide-track-width, 12px)"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
        />

        {/* Start endpoint marker */}
        {startPoint && (
          <circle
            data-heelslide-start
            cx={startPoint.x}
            cy={startPoint.y}
            r="var(--heelslide-track-start-radius, var(--heelslide-endpoint-size, var(--heelslide-start-radius, 6px)))"
            fill="var(--heelslide-track-bg, #cbd5e1)"
          />
        )}

        {/* Heel direction change corner markers */}
        {heelVertices.map((vertex, index) => {
          const isTarget = currentSegmentIndex === index;
          const isCleared = currentSegmentIndex > index;
          return (
            <g
              key={`heel-${vertex.x}-${vertex.y}-${index}`}
              data-heelslide-heel={index + 1}
              data-target={isTarget ? 'true' : 'false'}
              className={`heelslide-heel-group ${isTarget ? 'heelslide-target' : ''}`}
              style={{ counterIncrement: 'heelslide-heel' }}
            >
              {/* Clearance buffer ring */}
              <circle
                className="heelslide-heel-buffer"
                cx={vertex.x}
                cy={vertex.y}
                r="var(--heelslide-track-heel-radius, var(--heelslide-heel-radius, var(--heelslide-heel-size, 4px)))"
                fill="none"
                stroke="var(--heelslide-track-bg, #e2e8f0)"
                strokeWidth="var(--heelslide-heel-padding, 0px)"
              />
              {/* Heel marker circle */}
              <circle
                className="heelslide-heel-marker"
                cx={vertex.x}
                cy={vertex.y}
                r="var(--heelslide-track-heel-radius, var(--heelslide-heel-radius, var(--heelslide-heel-size, 4px)))"
                fill={
                  isCleared
                    ? 'var(--heelslide-heel-completed-color, var(--heelslide-track-active, #3b82f6))'
                    : isTarget
                    ? 'var(--heelslide-target-heel-bg, var(--heelslide-heel-bg, var(--heelslide-track-active, #3b82f6)))'
                    : 'var(--heelslide-heel-bg, var(--heelslide-heel-color, #94a3b8))'
                }
                stroke={
                  isTarget
                    ? 'var(--heelslide-target-heel-border-color, var(--heelslide-heel-border-color, #ffffff))'
                    : 'var(--heelslide-heel-border-color, transparent)'
                }
                strokeWidth={
                  isTarget
                    ? 'var(--heelslide-target-heel-border-width, var(--heelslide-heel-border-width, 2px))'
                    : 'var(--heelslide-heel-border-width, 0px)'
                }
              />
              {/* Numbered heel text */}
              {numberedHeels && (
                <text
                  className="heelslide-heel-text"
                  x={vertex.x}
                  y={vertex.y}
                  textAnchor="middle"
                  dominantBaseline="central"
                  fontFamily="var(--heelslide-heel-font-family, system-ui, -apple-system, sans-serif)"
                  fontSize="var(--heelslide-heel-font-size, 10px)"
                  fontWeight="var(--heelslide-heel-font-weight, 600)"
                  fill={
                    isTarget
                      ? 'var(--heelslide-target-heel-text-color, #ffffff)'
                      : 'var(--heelslide-heel-text-color, var(--heelslide-heel-color, #475569))'
                  }
                  style={{ pointerEvents: 'none', userSelect: 'none' }}
                >
                  {index + 1}
                </text>
              )}
            </g>
          );
        })}

        {/* End destination marker */}
        {endPoint && (
          <g
            data-heelslide-end-group
            data-target={isGoalTarget ? 'true' : 'false'}
            className={`heelslide-goal-group ${isGoalTarget ? 'heelslide-target' : ''}`}
          >
            <circle
              data-heelslide-end
              className="heelslide-end-marker"
              cx={endPoint.x}
              cy={endPoint.y}
              r="var(--heelslide-track-end-radius, var(--heelslide-end-radius, var(--heelslide-endpoint-size, 6px)))"
              fill={
                isGoalTarget
                  ? 'var(--heelslide-goal-bg, var(--heelslide-end-color, #10b981))'
                  : 'var(--heelslide-goal-bg, var(--heelslide-end-color, var(--heelslide-track-active, #3b82f6)))'
              }
              stroke={
                isGoalTarget
                  ? 'var(--heelslide-goal-border-color, #ffffff)'
                  : 'var(--heelslide-goal-border-color, transparent)'
              }
              strokeWidth={
                isGoalTarget
                  ? 'var(--heelslide-goal-border-width, 2px)'
                  : 'var(--heelslide-goal-border-width, 0px)'
              }
            />
          </g>
        )}
      </svg>

      {/* Draggable handle */}
      <div
        data-heelslide-handle
        style={{
          ...handleProps.style,
          width: 'var(--heelslide-handle-size, 32px)',
          height: 'var(--heelslide-handle-size, 32px)',
          backgroundColor:
            state === 'unlocked'
              ? 'var(--heelslide-success-color, #10b981)'
              : isDragging
              ? 'var(--heelslide-handle-active-bg, var(--heelslide-handle-bg, #1d4ed8))'
              : state === 'checkpoint'
              ? 'var(--heelslide-handle-checkpoint-bg, var(--heelslide-handle-active-bg, var(--heelslide-handle-bg, #2563eb)))'
              : 'var(--heelslide-handle-bg, var(--heelslide-slider-bg, var(--heelslide-handle-color, #2563eb)))',
          borderWidth: 'var(--heelslide-handle-border-width, 2px)',
          borderStyle: 'solid',
          borderColor:
            state === 'unlocked'
              ? 'var(--heelslide-success-color, #10b981)'
              : state === 'checkpoint'
              ? 'var(--heelslide-handle-checkpoint-border-color, var(--heelslide-handle-border-color, #f59e0b))'
              : 'var(--heelslide-handle-border-color, var(--heelslide-slider-border-color, #ffffff))',
          borderRadius: '50%',
          boxShadow:
            state === 'checkpoint'
              ? 'var(--heelslide-handle-checkpoint-shadow, 0 0 12px rgba(245, 158, 11, 0.6))'
              : 'var(--heelslide-handle-shadow, 0 2px 8px rgba(0, 0, 0, 0.15))',
          transform:
            isDragging || state === 'checkpoint'
              ? `${handleProps.style.transform ?? ''} scale(var(--heelslide-handle-active-scale, 1.05))`
              : handleProps.style.transform,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          pointerEvents: 'auto',
          transition: isDragging ? 'none' : 'left 0.15s ease-out, top 0.15s ease-out, transform 0.15s ease-out'
        }}
      >
        {children}
      </div>

      <span id={descriptionId} style={visuallyHidden}>
        {description}
      </span>

      {stepped ? (
        <span
          data-heelslide-live-region
          role="status"
          aria-live="polite"
          aria-atomic="true"
          style={visuallyHidden}
        >
          {announcement?.message ?? ''}
        </span>
      ) : null}
    </div>
  );
});

Heelslide.displayName = 'Heelslide';
